try {

    const l1 = [2, 4, 3].reverse();
    const l2 = [5, 6, 4].reverse();

    console.log(l1);

} catch (error) {
    console.error("Erro: ", error.message);
}